import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/foundation.dart';

/// Firebase service for authentication and cloud operations
class FirebaseService {
  static FirebaseService? _instance;
  static FirebaseService get instance => _instance ??= FirebaseService._();
  
  FirebaseService._();

  FirebaseAuth get auth => FirebaseAuth.instance;
  FirebaseFirestore get firestore => FirebaseFirestore.instance;
  FirebaseStorage get storage => FirebaseStorage.instance;

  bool _initialized = false;
  String? _verificationId;
  int? _resendToken;

  /// Initialize Firebase
  /// IMPORTANT: Run 'flutterfire configure' to generate firebase_options.dart
  Future<void> init() async {
    if (_initialized) return;

    try {
      // Try to initialize with firebase_options.dart (generated by flutterfire)
      // If file doesn't exist, this will throw an error
      await Firebase.initializeApp(
        // options: DefaultFirebaseOptions.currentPlatform, // Uncomment after running flutterfire configure
      );
      
      _initialized = true;
      debugPrint('✅ Firebase initialized successfully');
    } catch (e) {
      debugPrint('═══════════════════════════════════════════════════');
      debugPrint('⚠️  FIREBASE NOT CONFIGURED');
      debugPrint('═══════════════════════════════════════════════════');
      debugPrint('Firebase initialization failed: $e');
      debugPrint('');
      debugPrint('To fix this:');
      debugPrint('1. Install FlutterFire CLI: dart pub global activate flutterfire_cli');
      debugPrint('2. Run: flutterfire configure');
      debugPrint('3. Select your Firebase project');
      debugPrint('4. Uncomment the line in firebase_service.dart');
      debugPrint('');
      debugPrint('See FIREBASE_SETUP_GUIDE.md for detailed instructions');
      debugPrint('═══════════════════════════════════════════════════');
      debugPrint('');
      debugPrint('⚠️  App will continue WITHOUT Firebase features:');
      debugPrint('   - Phone authentication will not work');
      debugPrint('   - Cloud storage will not work');
      debugPrint('   - Analytics will not work');
      debugPrint('═══════════════════════════════════════════════════');
      
      // Continue without Firebase for development
      _initialized = false;
    }
  }

  // ═══════════════════════════════════════════════════════════════════════
  // PHONE AUTHENTICATION
  // ═══════════════════════════════════════════════════════════════════════

  /// Send OTP to phone number
  Future<bool> sendOTP({
    required String phoneNumber,
    required Function(String verificationId) onCodeSent,
    required Function(String error) onError,
    required Function() onTimeout,
  }) async {
    if (!_initialized) {
      onError('Firebase not initialized');
      return false;
    }

    try {
      // Format phone number to international format
      final formattedPhone = phoneNumber.startsWith('+91') 
          ? phoneNumber 
          : '+91$phoneNumber';

      await auth.verifyPhoneNumber(
        phoneNumber: formattedPhone,
        timeout: const Duration(seconds: 60),
        
        // Called when verification is completed automatically (Android only)
        verificationCompleted: (PhoneAuthCredential credential) async {
          debugPrint('✅ Auto verification completed');
          await auth.signInWithCredential(credential);
        },
        
        // Called when verification fails
        verificationFailed: (FirebaseAuthException e) {
          debugPrint('❌ Verification failed: ${e.message}');
          if (e.code == 'invalid-phone-number') {
            onError('Invalid phone number format');
          } else if (e.code == 'too-many-requests') {
            onError('Too many requests. Please try again later');
          } else {
            onError(e.message ?? 'Verification failed');
          }
        },
        
        // Called when OTP is sent successfully
        codeSent: (String verificationId, int? resendToken) {
          debugPrint('✅ OTP sent successfully');
          _verificationId = verificationId;
          _resendToken = resendToken;
          onCodeSent(verificationId);
        },
        
        // Called when auto-retrieval timeout
        codeAutoRetrievalTimeout: (String verificationId) {
          debugPrint('⏱️ Auto retrieval timeout');
          _verificationId = verificationId;
          onTimeout();
        },
        
        // Resend token from previous verification
        forceResendingToken: _resendToken,
      );

      return true;
    } catch (e) {
      debugPrint('❌ Send OTP error: $e');
      onError('Failed to send OTP: $e');
      return false;
    }
  }

  /// Verify OTP code
  Future<UserCredential?> verifyOTP({
    required String otp,
    String? verificationId,
  }) async {
    if (!_initialized) {
      throw Exception('Firebase not initialized');
    }

    try {
      final vid = verificationId ?? _verificationId;
      if (vid == null) {
        throw Exception('Verification ID not found. Please resend OTP');
      }

      // Create credential
      final credential = PhoneAuthProvider.credential(
        verificationId: vid,
        smsCode: otp,
      );

      // Sign in with credential
      final userCredential = await auth.signInWithCredential(credential);
      debugPrint('✅ OTP verified successfully: ${userCredential.user?.uid}');
      
      return userCredential;
    } on FirebaseAuthException catch (e) {
      debugPrint('❌ OTP verification error: ${e.message}');
      if (e.code == 'invalid-verification-code') {
        throw Exception('Invalid OTP code');
      } else if (e.code == 'session-expired') {
        throw Exception('OTP expired. Please request a new one');
      } else {
        throw Exception(e.message ?? 'Verification failed');
      }
    } catch (e) {
      debugPrint('❌ Verify OTP error: $e');
      throw Exception('Failed to verify OTP: $e');
    }
  }

  /// Resend OTP
  Future<bool> resendOTP({
    required String phoneNumber,
    required Function(String verificationId) onCodeSent,
    required Function(String error) onError,
  }) async {
    return await sendOTP(
      phoneNumber: phoneNumber,
      onCodeSent: onCodeSent,
      onError: onError,
      onTimeout: () {},
    );
  }

  // ═══════════════════════════════════════════════════════════════════════
  // USER MANAGEMENT
  // ═══════════════════════════════════════════════════════════════════════

  /// Get current user
  User? get currentUser => auth.currentUser;

  /// Check if user is signed in
  bool get isSignedIn => currentUser != null;

  /// Get user ID
  String? get userId => currentUser?.uid;

  /// Get user phone number
  String? get userPhone => currentUser?.phoneNumber;

  /// Sign out
  Future<void> signOut() async {
    await auth.signOut();
    _verificationId = null;
    _resendToken = null;
    debugPrint('✅ User signed out');
  }

  /// Delete user account
  Future<void> deleteAccount() async {
    final user = currentUser;
    if (user == null) return;
    
    // Delete user data from Firestore
    await firestore.collection('users').doc(user.uid).delete();
    
    // Delete user account
    await user.delete();
    debugPrint('✅ User account deleted');
  }

  // ═══════════════════════════════════════════════════════════════════════
  // FIRESTORE OPERATIONS
  // ═══════════════════════════════════════════════════════════════════════

  /// Save user data to Firestore
  Future<void> saveUserData(Map<String, dynamic> userData) async {
    if (!isSignedIn) return;
    
    await firestore.collection('users').doc(userId).set(
      {
        ...userData,
        'updated_at': FieldValue.serverTimestamp(),
      },
      SetOptions(merge: true),
    );
    debugPrint('✅ User data saved to Firestore');
  }

  /// Get user data from Firestore
  Future<Map<String, dynamic>?> getUserData() async {
    if (!isSignedIn) return null;
    
    final doc = await firestore.collection('users').doc(userId).get();
    return doc.data();
  }

  /// Update user field
  Future<void> updateUserField(String field, dynamic value) async {
    if (!isSignedIn) return;
    
    await firestore.collection('users').doc(userId).update({
      field: value,
      'updated_at': FieldValue.serverTimestamp(),
    });
  }

  /// Listen to user data changes
  Stream<Map<String, dynamic>?> watchUserData() {
    if (!isSignedIn) return Stream.value(null);
    
    return firestore
        .collection('users')
        .doc(userId)
        .snapshots()
        .map((snapshot) => snapshot.data());
  }

  // ═══════════════════════════════════════════════════════════════════════
  // AUTH STATE CHANGES
  // ═══════════════════════════════════════════════════════════════════════

  /// Listen to auth state changes
  Stream<User?> get authStateChanges => auth.authStateChanges();

  /// Listen to user changes (includes token refresh)
  Stream<User?> get userChanges => auth.userChanges();

  // ═══════════════════════════════════════════════════════════════════════
  // TOKEN MANAGEMENT
  // ═══════════════════════════════════════════════════════════════════════

  /// Get ID token for API calls
  Future<String?> getIdToken({bool forceRefresh = false}) async {
    return await currentUser?.getIdToken(forceRefresh);
  }

  /// Force refresh token
  Future<void> refreshToken() async {
    await currentUser?.getIdToken(true);
  }
}
