// GENERATED by scripts/gen_catalogue_specs.py from the client catalogue PDFs. Do not edit by hand.
// The stones table has no size / thickness / sqft-per-box data; these fill the gaps.
// patchHeightM is the real-world height of the AR texture photo: exact where the PDF gives the
// panel size, otherwise ESTIMATED (see the script) and meant to be tuned on a real device.

class CatalogueSpec {
  final String? size;
  final String? thickness;
  final double? sqftPerBox;
  final int? piecesPerBox;
  final double? patchHeightM;
  final String? arTexture;
  const CatalogueSpec({this.size, this.thickness, this.sqftPerBox, this.piecesPerBox, this.patchHeightM, this.arTexture});
}

class CatalogueSpecs {
  static String _norm(String s) => s.toLowerCase().replaceAll(RegExp(r'\b(series|collection|ledge)\b'), '').replaceAll(RegExp(r'\s+'), ' ').trim();

  /// Spec for a stone (matched by collection + name), or null for anything not in the catalogue PDFs.
  static CatalogueSpec? forStone(String collection, String name) {
    final c = collection.toLowerCase();
    if (c.contains('exclusive')) return _exclusive[name.trim().toLowerCase()];
    if (c.contains('premium surface') || c.contains('premium 3d')) return _surface3d[name.trim().toLowerCase()];
    return _series[_norm(collection)];
  }

  /// Every bundled clean AR texture named in the specs (used by tests to check the files exist).
  static Iterable<String> get bundledTextures => [
        ..._series.values, ..._surface3d.values, ..._exclusive.values,
      ].map((s) => s.arTexture).whereType<String>();

  static const _series = <String, CatalogueSpec>{
    'alpine': CatalogueSpec(size: '640 × 290 mm', thickness: '20 mm', sqftPerBox: 8.52, patchHeightM: 0.9, arTexture: null),
    'andorra': CatalogueSpec(size: '500 × 130 mm', thickness: '45 mm', sqftPerBox: 5.4, patchHeightM: 1.3, arTexture: null),
    'castle': CatalogueSpec(size: '305 × 165 mm', thickness: '25 mm', sqftPerBox: 6.6, patchHeightM: 0.55, arTexture: null),
    'cave': CatalogueSpec(size: '300 × 300 mm', thickness: '15 mm', sqftPerBox: 7.0, patchHeightM: 1.0, arTexture: null),
    'classic': CatalogueSpec(size: '340 × 100 mm', thickness: '20 mm', sqftPerBox: 11.4, patchHeightM: 0.9, arTexture: null),
    'colonial brick': CatalogueSpec(size: '235 × 65 mm', thickness: '15 mm', sqftPerBox: 7.2, patchHeightM: 0.65, arTexture: null),
    'country': CatalogueSpec(size: '500 × 100 mm', thickness: '30 mm', sqftPerBox: 7.5, patchHeightM: 1.1, arTexture: null),
    'cuarzo': CatalogueSpec(size: '500 × 125 mm', thickness: '25 mm', sqftPerBox: 9.35, patchHeightM: 1.25, arTexture: null),
    'egyptian': CatalogueSpec(size: '600 × 100 mm', thickness: '20 mm', sqftPerBox: 6.45, patchHeightM: 0.35, arTexture: 'assets/ar_textures/egyptian.jpg'),
    'european stack': CatalogueSpec(size: null, thickness: '35 mm', sqftPerBox: 5.75, patchHeightM: 0.9, arTexture: null),
    'flora': CatalogueSpec(size: '450 × 300 mm', thickness: '20 mm', sqftPerBox: null, patchHeightM: 0.6, arTexture: null),
    'florentine': CatalogueSpec(size: '755 × 125 mm', thickness: '20 mm', sqftPerBox: 8.32, patchHeightM: 1.1, arTexture: null),
    'foliage': CatalogueSpec(size: '600 × 300 mm', thickness: '15 mm', sqftPerBox: 11.55, patchHeightM: 0.6, arTexture: null),
    'fossile rock': CatalogueSpec(size: null, thickness: '50 mm', sqftPerBox: 5.5, patchHeightM: 0.35, arTexture: 'assets/ar_textures/fossil_rock.jpg'),
    'grande': CatalogueSpec(size: '490 × 195 mm', thickness: '35 mm', sqftPerBox: 7.0, patchHeightM: 1.3, arTexture: null),
    'hexa': CatalogueSpec(size: '230 × 200 mm', thickness: '20 mm', sqftPerBox: 6.4, patchHeightM: 0.7, arTexture: null),
    'lakhori brick': CatalogueSpec(size: '535 × 160 mm', thickness: '35 mm', sqftPerBox: 6.4, patchHeightM: 0.6, arTexture: 'assets/ar_textures/lakhori_brick.jpg'),
    'milano': CatalogueSpec(size: '895 × 595 mm', thickness: '25 mm', sqftPerBox: 5.81, patchHeightM: 0.6, arTexture: null),
    'modena': CatalogueSpec(size: '600 × 150 mm', thickness: '15 mm', sqftPerBox: 11.55, patchHeightM: 0.9, arTexture: null),
    'mountain': CatalogueSpec(size: '500 × 100 mm', thickness: '30 mm', sqftPerBox: 7.5, patchHeightM: 1.1, arTexture: null),
    'opus': CatalogueSpec(size: null, thickness: '30 mm', sqftPerBox: 7.35, patchHeightM: 1.2, arTexture: null),
    'rockface linear': CatalogueSpec(size: '445 × 110 mm', thickness: '25 mm', sqftPerBox: 6.38, patchHeightM: 1.0, arTexture: null),
    'rustic brick': CatalogueSpec(size: '195 × 60 mm', thickness: '10 mm', sqftPerBox: 8.12, patchHeightM: 0.56, arTexture: null),
    'sierra': CatalogueSpec(size: null, thickness: '35 mm', sqftPerBox: 6.5, patchHeightM: 0.8, arTexture: null),
    'sleepwood': CatalogueSpec(size: '580 × 130 mm', thickness: '25 mm', sqftPerBox: 6.25, patchHeightM: 1.3, arTexture: null),
    'tarnished brick': CatalogueSpec(size: '190 × 65 mm', thickness: '15 mm', sqftPerBox: 7.9, patchHeightM: 0.6, arTexture: null),
    'tevoli': CatalogueSpec(size: '600 × 150 mm', thickness: '30 mm', sqftPerBox: 7.42, patchHeightM: 0.9, arTexture: null),
    'travertine': CatalogueSpec(size: '755 × 500 mm', thickness: '15 mm', sqftPerBox: 8.16, patchHeightM: 1.0, arTexture: null),
    'vantage': CatalogueSpec(size: '410 × 150 mm', thickness: '25 mm', sqftPerBox: 6.45, patchHeightM: 1.0, arTexture: null),
    'veines': CatalogueSpec(size: '510 × 250 mm', thickness: '15 mm', sqftPerBox: 15.12, patchHeightM: 1.0, arTexture: null),
    'venetian': CatalogueSpec(size: '500 × 120 mm', thickness: '20 mm', sqftPerBox: 8.1, patchHeightM: 1.3, arTexture: null),
    'vine': CatalogueSpec(size: '600 × 200 mm', thickness: '25 mm', sqftPerBox: 7.74, patchHeightM: 0.8, arTexture: null),
    'weave': CatalogueSpec(size: '300 × 300 mm', thickness: '25 mm', sqftPerBox: 7.0, patchHeightM: 0.75, arTexture: null),
  };

  static const _surface3d = <String, CatalogueSpec>{
    '2-barcode': CatalogueSpec(size: '1066 × 281 mm', thickness: '30 mm', sqftPerBox: 13.11, piecesPerBox: 3, patchHeightM: 1.0, arTexture: 'assets/ar_textures/3d_2_barcode.jpg'),
    '5-barcode': CatalogueSpec(size: '1066 × 381 mm', thickness: '30 mm', sqftPerBox: 13.11, piecesPerBox: 3, patchHeightM: 1.0, arTexture: 'assets/ar_textures/3d_5_barcode.jpg'),
    'archo': CatalogueSpec(size: '609.6 × 457.2 mm', thickness: '30 mm', sqftPerBox: 4.0, piecesPerBox: 4, patchHeightM: 1.0, arTexture: 'assets/ar_textures/3d_archo.jpg'),
    'athena': CatalogueSpec(size: '200 × 100 mm', thickness: '30 mm', sqftPerBox: 5.04, piecesPerBox: 24, patchHeightM: 1.0, arTexture: 'assets/ar_textures/3d_athena.jpg'),
    'blanco': CatalogueSpec(size: '400 × 100 mm', thickness: '30 mm', sqftPerBox: 10.32, piecesPerBox: 24, patchHeightM: 1.0, arTexture: 'assets/ar_textures/3d_blanco.jpg'),
    'cairo': CatalogueSpec(size: '424 × 248 mm', thickness: '35 mm', sqftPerBox: 6.0, piecesPerBox: 5, patchHeightM: 1.0, arTexture: 'assets/ar_textures/3d_cairo.jpg'),
    'cosmic flutes': CatalogueSpec(size: '762 × 381 mm', thickness: '30 mm', sqftPerBox: 6.25, piecesPerBox: 2, patchHeightM: 1.0, arTexture: 'assets/ar_textures/3d_cosmic_flutes.jpg'),
    'feather': CatalogueSpec(size: '400 × 100 mm', thickness: '30 mm', sqftPerBox: 10.32, piecesPerBox: 24, patchHeightM: 1.0, arTexture: 'assets/ar_textures/3d_feather.jpg'),
    'ferro': CatalogueSpec(size: '609.60 × 152.40 mm', thickness: '30 mm', sqftPerBox: 10.0, piecesPerBox: 10, patchHeightM: 1.0, arTexture: 'assets/ar_textures/3d_ferro.jpg'),
    'flute fusion': CatalogueSpec(size: '300 × 300 mm', thickness: '30 mm', sqftPerBox: 8.0, piecesPerBox: 8, patchHeightM: 1.0, arTexture: 'assets/ar_textures/3d_flute_fusion.jpg'),
    'granito': CatalogueSpec(size: '450 × 950 mm', thickness: '30 mm', sqftPerBox: 13.07, piecesPerBox: 3, patchHeightM: 1.0, arTexture: 'assets/ar_textures/3d_granito.jpg'),
    'hydes': CatalogueSpec(size: '651 × 336 mm', thickness: '70 mm', sqftPerBox: 4.5, piecesPerBox: 2, patchHeightM: 1.0, arTexture: 'assets/ar_textures/3d_hydes.jpg'),
    'kite': CatalogueSpec(size: '152.4 × 304.8 mm', thickness: '25 mm', sqftPerBox: 4.0, piecesPerBox: 16, patchHeightM: 1.0, arTexture: 'assets/ar_textures/3d_kite.jpg'),
    'mobis': CatalogueSpec(size: '609.60 × 152.40 mm', thickness: '30 mm', sqftPerBox: 10.0, piecesPerBox: 10, patchHeightM: 1.0, arTexture: 'assets/ar_textures/3d_mobis.jpg'),
    'pietra': CatalogueSpec(size: '400 × 100 mm', thickness: '30 mm', sqftPerBox: 10.32, piecesPerBox: 24, patchHeightM: 1.0, arTexture: 'assets/ar_textures/3d_pietra.jpg'),
    'rover': CatalogueSpec(size: '508 × 101.6 mm', thickness: '35 mm', sqftPerBox: 6.6, piecesPerBox: 12, patchHeightM: 1.0, arTexture: 'assets/ar_textures/3d_rover.jpg'),
    's-wave': CatalogueSpec(size: '1250 × 250 mm', thickness: '40 mm', sqftPerBox: 6.72, piecesPerBox: 2, patchHeightM: 1.0, arTexture: 'assets/ar_textures/3d_s_wave.jpg'),
    'scale': CatalogueSpec(size: '300 × 300 mm', thickness: '35 mm', sqftPerBox: 8.0, piecesPerBox: 8, patchHeightM: 1.0, arTexture: 'assets/ar_textures/3d_scale.jpg'),
    'toran': CatalogueSpec(size: '900 × 300 mm', thickness: '30 mm', sqftPerBox: 9.0, piecesPerBox: 3, patchHeightM: 1.0, arTexture: 'assets/ar_textures/3d_toran.jpg'),
    'toran 2.0': CatalogueSpec(size: '900 × 300 mm', thickness: '43 mm', sqftPerBox: 6.0, piecesPerBox: 2, patchHeightM: 1.0, arTexture: 'assets/ar_textures/3d_toran_2_0.jpg'),
    'vegas': CatalogueSpec(size: '400 × 100 mm', thickness: '30 mm', sqftPerBox: 10.32, piecesPerBox: 24, patchHeightM: 1.0, arTexture: 'assets/ar_textures/3d_vegas.jpg'),
    'verona': CatalogueSpec(size: '300 × 80 mm', thickness: '30 mm', sqftPerBox: 7.2, piecesPerBox: 36, patchHeightM: 1.0, arTexture: 'assets/ar_textures/3d_verona.jpg'),
  };

  static const _exclusive = <String, CatalogueSpec>{
    'arctic chevron strata': CatalogueSpec(size: null, thickness: '15 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_arctic_chevron_strata.jpg'),
    'baroque copper patina': CatalogueSpec(size: '600 × 1200 mm', thickness: '15-20 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_baroque_copper_patina.jpg'),
    'botanical copper pattern': CatalogueSpec(size: '300 × 450 mm', thickness: '15-20 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_botanical_copper_pattern.jpg'),
    'brushed alloy reveal': CatalogueSpec(size: '150 × 600 mm', thickness: '15 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_brushed_alloy_reveal.jpg'),
    'copper fossil pattern': CatalogueSpec(size: '300 × 300 mm', thickness: '15 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_copper_fossil_pattern.jpg'),
    'diamond plate matrix': CatalogueSpec(size: '300 × 600 mm', thickness: '15 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_diamond_plate_matrix.jpg'),
    'fleur lattice panel': CatalogueSpec(size: '600 × 1200 mm', thickness: '15-20 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_fleur_lattice_panel.jpg'),
    'fluid wave panel': CatalogueSpec(size: '600 × 1200 mm', thickness: '15-20 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_fluid_wave_panel.jpg'),
    'golden arc rhythm': CatalogueSpec(size: null, thickness: '15-20 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_golden_arc_rhythm.jpg'),
    'golden hexa pattern': CatalogueSpec(size: '200 × 230.94 mm', thickness: '15-20 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_golden_hexa_pattern.jpg'),
    'golden stud matrix': CatalogueSpec(size: '30 × 60 mm', thickness: '15 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_golden_stud_matrix.jpg'),
    'golden terrain mosaic': CatalogueSpec(size: '200 × 200 mm', thickness: '15 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_golden_terrain_mosaic.jpg'),
    'indigo linear weave': CatalogueSpec(size: null, thickness: '15 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_indigo_linear_weave.jpg'),
    'industrial strata pattern': CatalogueSpec(size: null, thickness: '15 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_industrial_strata_pattern.jpg'),
    'ivory fossil mosaic': CatalogueSpec(size: '300 × 300 mm', thickness: '15-20 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_ivory_fossil_mosaic.jpg'),
    'ivory metallic strata': CatalogueSpec(size: '100 × 600 mm', thickness: '15-20 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_ivory_metallic_strata.jpg'),
    'linear alloy strata': CatalogueSpec(size: '75 × 600 mm', thickness: '15 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_linear_alloy_strata.jpg'),
    'lunar nickel pattern': CatalogueSpec(size: '200 × 200 mm', thickness: '15 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_lunar_nickel_pattern.jpg'),
    'midnight scallop mosaic': CatalogueSpec(size: '600 × 1200 mm', thickness: '15-20 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_midnight_scallop_mosaic.jpg'),
    'monochrome hexa pattern': CatalogueSpec(size: '200 × 230.94 mm', thickness: '15-20 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_monochrome_hexa_pattern.jpg'),
    'monochrome texture pattern': CatalogueSpec(size: '300 × 300 mm', thickness: '15-20 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_monochrome_texture_pattern.jpg'),
    'mosaic rhythm grid': CatalogueSpec(size: '300 × 300 mm', thickness: '15 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_mosaic_rhythm_grid.jpg'),
    'nordic mosaic grid': CatalogueSpec(size: '48 × 98 mm', thickness: '15 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_nordic_mosaic_grid.jpg'),
    'ornamental stone strata': CatalogueSpec(size: null, thickness: '15-20 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_ornamental_stone_strata.jpg'),
    'ornate nickel scales': CatalogueSpec(size: '600 × 1200 mm', thickness: '15-20 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_ornate_nickel_scales.jpg'),
    'patina strata': CatalogueSpec(size: '100 × 600 mm', thickness: '25-30 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_patina_strata.jpg'),
    'perforated metal matrix': CatalogueSpec(size: '300 × 600 mm', thickness: '15 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_perforated_metal_matrix.jpg'),
    'river pebble panel': CatalogueSpec(size: '600 × 1200 mm', thickness: '30-35 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_river_pebble_panel.jpg'),
    'riveted bronze grid': CatalogueSpec(size: '300 × 600 mm', thickness: '15 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_riveted_bronze_grid.jpg'),
    'riveted steel patchwork': CatalogueSpec(size: '300 × 300 mm', thickness: '15 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_riveted_steel_patchwork.jpg'),
    'sacred bronze tapestry': CatalogueSpec(size: '300 × 300 mm', thickness: '15-20 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_sacred_bronze_tapestry.jpg'),
    'textured bronze patchwork': CatalogueSpec(size: null, thickness: '15 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_textured_bronze_patchwork.jpg'),
    'timber flow panel': CatalogueSpec(size: '600 × 1200 mm', thickness: '30-35 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_timber_flow_panel.jpg'),
    'tribal nickel rhythm': CatalogueSpec(size: '200 × 400 mm', thickness: '15 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_tribal_nickel_rhythm.jpg'),
    'turquoise fleur heritage': CatalogueSpec(size: '600 × 1200 mm', thickness: '15-20 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_turquoise_fleur_heritage.jpg'),
    'turquoise floral heritage': CatalogueSpec(size: '300 × 300 mm', thickness: '15 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_turquoise_floral_heritage.jpg'),
    'turquoise lava panel': CatalogueSpec(size: '600 × 1200 mm', thickness: '30-35 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_turquoise_lava_panel.jpg'),
    'turquoise scallop pattern': CatalogueSpec(size: '600 × 1200 mm', thickness: '20-25 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_turquoise_scallop_pattern.jpg'),
    'verdigris copper bloom': CatalogueSpec(size: null, thickness: '15-20 mm', patchHeightM: 0.6, arTexture: 'assets/ar_textures/ex_verdigris_copper_bloom.jpg'),
  };
}
