#!/usr/bin/env dart
// Seed script for Supabase database
// Run with: dart run scripts/seed_database.dart

import 'dart:convert';
import 'dart:io';
import 'package:supabase/supabase.dart';

/// This script seeds the Supabase database with initial product data.
/// It reads from the mock data and inserts into Supabase.

final supabaseUrl = 'https://jrrmjtbauimrrxwjvmzh.supabase.co';
final supabaseAnonKey = 'sb_publishable_l0K305hiCMwZ8Mh3lON3YQ_ueSMXo4a';

void main() async {
  print('🌱 Starting database seed...');
  
  final supabase = SupabaseClient(supabaseUrl, supabaseAnonKey);
  
  try {
    // Seed collections
    await seedCollections(supabase);
    
    // Seed stones
    await seedStones(supabase);
    
    // Seed dealers
    await seedDealers(supabase);
    
    print('✅ Database seed completed successfully!');
  } catch (e) {
    print('❌ Seed failed: $e');
    exit(1);
  }
}

Future<void> seedCollections(SupabaseClient supabase) async {
  print('📦 Seeding collections...');
  
  final collections = [
    {
      'name': 'Grande Ledge Series',
      'slug': 'grande-ledge-series',
      'description': 'Rugged textures and clean lines blending modern elegance with natural charm',
      'image_url': null,
      'sort_order': 1,
      'active': true,
    },
    {
      'name': 'Country Ledge Series',
      'slug': 'country-ledge-series',
      'description': 'Captures the essence of rustic charm with natural stone textures and earthy tones',
      'image_url': null,
      'sort_order': 2,
      'active': true,
    },
    {
      'name': 'Mountain Ledge Series',
      'slug': 'mountain-ledge-series',
      'description': 'Inspired by rugged mountain ranges with coarse unpolished textures',
      'image_url': null,
      'sort_order': 3,
      'active': true,
    },
    {
      'name': 'Opus Ledge Series',
      'slug': 'opus-ledge-series',
      'description': 'Precision set patterns offering seamless installation and insulation',
      'image_url': null,
      'sort_order': 4,
      'active': true,
    },
    {
      'name': 'Classic Ledge Series',
      'slug': 'classic-ledge-series',
      'description': 'Timeless sophistication with clean horizontal lines and refined textures',
      'image_url': null,
      'sort_order': 5,
      'active': true,
    },
    {
      'name': 'Vantage Series',
      'slug': 'vantage-series',
      'description': 'Combines classic aesthetics with modern lightweight functionality',
      'image_url': null,
      'sort_order': 6,
      'active': true,
    },
    {
      'name': 'Rockface Linear Series',
      'slug': 'rockface-linear-series',
      'description': 'Sleek linear designs blending natural textures with modern aesthetics',
      'image_url': null,
      'sort_order': 7,
      'active': true,
    },
    {
      'name': 'Castle Ledge Series',
      'slug': 'castle-ledge-series',
      'description': 'Bold irregular stones and intricate details inspired by medieval architecture',
      'image_url': null,
      'sort_order': 8,
      'active': true,
    },
    {
      'name': 'Cuarzo Series',
      'slug': 'cuarzo-series',
      'description': 'Inspired by the brilliance of quartz with shimmering refined textures',
      'image_url': null,
      'sort_order': 9,
      'active': true,
    },
    {
      'name': 'Rustic Brick Series',
      'slug': 'rustic-brick-series',
      'description': 'Vintage charm and weathered brickwork inspired by old-world European villages',
      'image_url': null,
      'sort_order': 10,
      'active': true,
    },
    {
      'name': 'Tarnished Brick Series',
      'slug': 'tarnished-brick-series',
      'description': 'Antique patina and soft weathered edges for rustic and vintage spaces',
      'image_url': null,
      'sort_order': 11,
      'active': true,
    },
    {
      'name': 'Florentine Series',
      'slug': 'florentine-series',
      'description': 'Intricate detailing and refined textures inspired by Florentine architecture',
      'image_url': null,
      'sort_order': 12,
      'active': true,
    },
    {
      'name': 'Foliage Series',
      'slug': 'foliage-series',
      'description': 'Botanical leaf patterns and organic textures reflecting nature harmony',
      'image_url': null,
      'sort_order': 13,
      'active': true,
    },
    {
      'name': 'Hexa Series',
      'slug': 'hexa-series',
      'description': 'Striking modern geometric hexagonal designs with precision natural stone',
      'image_url': null,
      'sort_order': 14,
      'active': true,
    },
    {
      'name': 'Milano Series',
      'slug': 'milano-series',
      'description': 'Milanese elegance with clean lines, smooth finishes, and contemporary tones',
      'image_url': null,
      'sort_order': 15,
      'active': true,
    },
    {
      'name': 'Alpine Series',
      'slug': 'alpine-series',
      'description': 'Serene beauty of alpine landscapes with soft textures and tranquil tones',
      'image_url': null,
      'sort_order': 16,
      'active': true,
    },
    {
      'name': 'Designer 3D Collection',
      'slug': 'designer-3d-collection',
      'description': 'Premium 3D decorative wall panels with geometric patterns',
      'image_url': null,
      'sort_order': 17,
      'active': true,
    },
  ];
  
  for (final collection in collections) {
    await supabase.from('collections').upsert(collection, onConflict: 'slug');
  }
  print('✅ Collections seeded');
}

Future<void> seedStones(SupabaseClient supabase) async {
  print('🪨 Seeding stones...');
  
  // Get collection IDs
  final collectionsData = await supabase.from('collections').select('id, slug');
  final collectionMap = {for (var c in collectionsData) c['slug']: c['id']};
  
  final stones = [
    {
      'name': 'Grande Ledge TA02',
      'slug': 'grande-ledge-ta02',
      'product_code': 'TA02',
      'collection_id': collectionMap['grande-ledge-series'],
      'category': 'Ledge Stone',
      'description': 'Premium natural stone cladding with deep texture and rustic charm. Perfect for exterior and interior feature walls.',
      'short_description': 'Premium natural stone cladding with deep texture',
      'price_per_sqft': 375,
      'price_per_unit': 375,
      'currency': 'INR',
      'discount_percent': 0,
      'moq': 1,
      'length_cm': 60,
      'width_cm': 15,
      'thickness_mm': 19,
      'weight_kg': 25,
      'coverage_sqft': 10.5,
      'finish': 'Natural',
      'material': 'Natural Stone',
      'colors': ['Beige', 'Grey', 'Brown'],
      'patterns': ['Rough Ledge'],
      'origin': 'India',
      'images': ['assets/images/grande_ledge_ta02.png', 'assets/images/hero_banner_1.png'],
      'thumbnail_url': 'assets/images/grande_ledge_ta02.png',
      'model_3d_url': null,
      'video_url': null,
      'catalogue_pdf_url': null,
      'stock_status': 'in_stock',
      'stock_quantity': 150,
      'lead_time_days': 7,
      'tags': ['Living Room', 'Lobby', 'Feature Wall', 'Hotel Interior'],
      'meta_title': 'Grande Ledge TA02 - Premium Stone Cladding',
      'meta_description': 'Premium natural stone cladding with deep texture and rustic charm.',
      'active': true,
      'featured': true,
      'sort_order': 1,
    },
    {
      'name': 'Classic Ledge 07',
      'slug': 'classic-ledge-07',
      'product_code': 'Classic 07',
      'collection_id': collectionMap['classic-ledge-series'],
      'category': 'Ledge Stone',
      'description': 'Timeless classic ledge stone with sophisticated layered design. Ideal for elegant architectural spaces.',
      'short_description': 'Timeless classic ledge stone with layered design',
      'price_per_sqft': 425,
      'price_per_unit': 425,
      'currency': 'INR',
      'discount_percent': 0,
      'moq': 1,
      'length_cm': 60,
      'width_cm': 15,
      'thickness_mm': 19,
      'weight_kg': 24,
      'coverage_sqft': 10.5,
      'finish': 'Natural',
      'material': 'Natural Stone',
      'colors': ['Grey', 'Charcoal', 'Silver'],
      'patterns': ['Stacked Ledge'],
      'origin': 'India',
      'images': ['assets/images/classic_ledge_07.png'],
      'thumbnail_url': 'assets/images/classic_ledge_07.png',
      'model_3d_url': null,
      'video_url': null,
      'catalogue_pdf_url': null,
      'stock_status': 'in_stock',
      'stock_quantity': 200,
      'lead_time_days': 7,
      'tags': ['Living Room', 'Office', 'Reception', 'Commercial'],
      'meta_title': 'Classic Ledge 07 - Timeless Stone Cladding',
      'meta_description': 'Timeless classic ledge stone with sophisticated layered design.',
      'active': true,
      'featured': true,
      'sort_order': 2,
    },
    {
      'name': 'Opus Ledge 15',
      'slug': 'opus-ledge-15',
      'product_code': 'Opus 15',
      'collection_id': collectionMap['opus-ledge-series'],
      'category': 'Ledge Stone',
      'description': 'Modern opus pattern ledge stone with irregular shapes creating a contemporary aesthetic.',
      'short_description': 'Modern opus pattern ledge stone with irregular shapes',
      'price_per_sqft': 375,
      'price_per_unit': 375,
      'currency': 'INR',
      'discount_percent': 0,
      'moq': 1,
      'length_cm': 60,
      'width_cm': 15,
      'thickness_mm': 19,
      'weight_kg': 23,
      'coverage_sqft': 10.5,
      'finish': 'Natural',
      'material': 'Natural Stone',
      'colors': ['Sandstone', 'Brown', 'Mixed'],
      'patterns': ['Irregular Ledge'],
      'origin': 'India',
      'images': ['assets/images/opus_ledge_15.png'],
      'thumbnail_url': 'assets/images/opus_ledge_15.png',
      'model_3d_url': null,
      'video_url': null,
      'catalogue_pdf_url': null,
      'stock_status': 'in_stock',
      'stock_quantity': 120,
      'lead_time_days': 7,
      'tags': ['Feature Wall', 'Restaurant', 'Bar', 'Modern Interior'],
      'meta_title': 'Opus Ledge 15 - Modern Opus Pattern Stone',
      'meta_description': 'Modern opus pattern ledge stone with irregular shapes.',
      'active': true,
      'featured': false,
      'sort_order': 3,
    },
    {
      'name': 'Verona 3D Panel',
      'slug': 'verona-3d-panel',
      'product_code': 'VERONA',
      'collection_id': collectionMap['designer-3d-collection'],
      'category': '3D Wall Panels',
      'description': 'Elegant 3D decorative wall panel with geometric patterns. Premium architectural element for luxury spaces.',
      'short_description': 'Elegant 3D decorative wall panel with geometric patterns',
      'price_per_sqft': 550,
      'price_per_unit': 550,
      'currency': 'INR',
      'discount_percent': 0,
      'moq': 1,
      'length_cm': 60,
      'width_cm': 60,
      'thickness_mm': 25,
      'weight_kg': 30,
      'coverage_sqft': 12.0,
      'finish': 'Polished',
      'material': 'Natural Stone',
      'colors': ['White', 'Grey', 'Black', 'Beige'],
      'patterns': ['3D Geometric'],
      'origin': 'Italy',
      'images': ['assets/images/verona_3d.png', 'assets/images/onboarding_2.png'],
      'thumbnail_url': 'assets/images/verona_3d.png',
      'model_3d_url': null,
      'video_url': null,
      'catalogue_pdf_url': null,
      'stock_status': 'in_stock',
      'stock_quantity': 80,
      'lead_time_days': 14,
      'tags': ['Living Room', 'Bedroom', 'Hotel Lobby', 'Office'],
      'meta_title': 'Verona 3D Panel - Luxury 3D Wall Panel',
      'meta_description': 'Elegant 3D decorative wall panel with geometric patterns.',
      'active': true,
      'featured': true,
      'sort_order': 4,
    },
    {
      'name': 'Athena 3D Panel',
      'slug': 'athena-3d-panel',
      'product_code': 'ATHENA',
      'collection_id': collectionMap['designer-3d-collection'],
      'category': '3D Wall Panels',
      'description': 'Sculptural 3D panel inspired by classical Greek architecture. Creates stunning shadow lines under accent lighting.',
      'short_description': 'Sculptural 3D panel inspired by classical Greek architecture',
      'price_per_sqft': 580,
      'price_per_unit': 580,
      'currency': 'INR',
      'discount_percent': 0,
      'moq': 1,
      'length_cm': 60,
      'width_cm': 60,
      'thickness_mm': 30,
      'weight_kg': 35,
      'coverage_sqft': 12.0,
      'finish': 'Honed',
      'material': 'Natural Stone',
      'colors': ['Snow White', 'Cream', 'Charcoal'],
      'patterns': ['Sculptural Wave'],
      'origin': 'Italy',
      'images': ['assets/images/athena_3d.png', 'assets/images/onboarding_3.png'],
      'thumbnail_url': 'assets/images/athena_3d.png',
      'model_3d_url': null,
      'video_url': null,
      'catalogue_pdf_url': null,
      'stock_status': 'in_stock',
      'stock_quantity': 65,
      'lead_time_days': 14,
      'tags': ['Living Room', 'Master Suite', 'Villa Lobby', 'Exterior Accent'],
      'meta_title': 'Athena 3D Panel - Sculptural 3D Wall Panel',
      'meta_description': 'Sculptural 3D panel inspired by classical Greek architecture.',
      'active': true,
      'featured': true,
      'sort_order': 5,
    },
    {
      'name': 'Vantage V12',
      'slug': 'vantage-v12',
      'product_code': 'V12',
      'collection_id': collectionMap['vantage-series'],
      'category': 'Linear Stone',
      'description': 'Sleek linear stone design with narrow striping for modern architectural facades and feature walls.',
      'short_description': 'Sleek linear stone design for modern facades',
      'price_per_sqft': 395,
      'price_per_unit': 395,
      'currency': 'INR',
      'discount_percent': 0,
      'moq': 1,
      'length_cm': 60,
      'width_cm': 15,
      'thickness_mm': 19,
      'weight_kg': 22,
      'coverage_sqft': 10.5,
      'finish': 'Natural',
      'material': 'Natural Stone',
      'colors': ['Grey', 'White', 'Black'],
      'patterns': ['Linear Ledge'],
      'origin': 'India',
      'images': ['assets/images/vantage_v12.png'],
      'thumbnail_url': 'assets/images/vantage_v12.png',
      'model_3d_url': null,
      'video_url': null,
      'catalogue_pdf_url': null,
      'stock_status': 'in_stock',
      'stock_quantity': 100,
      'lead_time_days': 7,
      'tags': ['Modern Home', 'Loft', 'Studio', 'Contemporary Office'],
      'meta_title': 'Vantage V12 - Linear Stone Design',
      'meta_description': 'Sleek linear stone design with narrow striping.',
      'active': true,
      'featured': false,
      'sort_order': 6,
    },
    {
      'name': 'Mountain Ledge M08',
      'slug': 'mountain-ledge-m08',
      'product_code': 'M08',
      'collection_id': collectionMap['mountain-ledge-series'],
      'category': 'Ledge Stone',
      'description': 'Rugged mountain-inspired ledge stone with natural texture and earthy tones.',
      'short_description': 'Rugged mountain-inspired ledge stone',
      'price_per_sqft': 410,
      'price_per_unit': 410,
      'currency': 'INR',
      'discount_percent': 0,
      'moq': 1,
      'length_cm': 60,
      'width_cm': 15,
      'thickness_mm': 22,
      'weight_kg': 28,
      'coverage_sqft': 10.5,
      'finish': 'Natural',
      'material': 'Natural Stone',
      'colors': ['Brown', 'Rust', 'Mixed Earth Tones'],
      'patterns': ['Rough Mountain'],
      'origin': 'India',
      'images': ['assets/images/mountain_ledge_m08.png'],
      'thumbnail_url': 'assets/images/mountain_ledge_m08.png',
      'model_3d_url': null,
      'video_url': null,
      'catalogue_pdf_url': null,
      'stock_status': 'in_stock',
      'stock_quantity': 180,
      'lead_time_days': 7,
      'tags': ['Exterior', 'Villa', 'Resort', 'Garden Wall'],
      'meta_title': 'Mountain Ledge M08 - Rugged Mountain Stone',
      'meta_description': 'Rugged mountain-inspired ledge stone with natural texture.',
      'active': true,
      'featured': false,
      'sort_order': 7,
    },
  ];
  
  for (final stone in stones) {
    await supabase.from('stones').upsert(stone, onConflict: 'slug');
  }
  print('✅ Stones seeded');
}

Future<void> seedDealers(SupabaseClient supabase) async {
  print('🏪 Seeding dealers...');
  
  final dealers = [
    {
      'name': 'Grazia Stones Flagship Experience Center',
      'company': 'Grazia Stones',
      'phone': '+91 9839846105',
      'email': 'kanpur@graziastones.com',
      'address': '123/477, Kalpi Road, Fazalganj',
      'city': 'Kanpur',
      'state': 'Uttar Pradesh',
      'pincode': '208012',
      'latitude': 26.4499,
      'longitude': 80.3319,
      'rating': 5.0,
      'verified': true,
      'active': true,
    },
    {
      'name': 'Grazia Premium Showroom',
      'company': 'Grazia Stones',
      'phone': '+91 98765 43210',
      'email': 'mumbai@graziastones.com',
      'address': '42 Design District, MG Road',
      'city': 'Mumbai',
      'state': 'Maharashtra',
      'pincode': '400001',
      'latitude': 19.0760,
      'longitude': 72.8777,
      'rating': 4.9,
      'verified': true,
      'active': true,
    },
    {
      'name': 'StoneWorld Architects Hub',
      'company': 'StoneWorld',
      'phone': '+91 11 2345 6789',
      'email': 'delhi@stoneworld.com',
      'address': '15 Connaught Place',
      'city': 'New Delhi',
      'state': 'Delhi',
      'pincode': '110001',
      'latitude': 28.6139,
      'longitude': 77.2090,
      'rating': 4.7,
      'verified': true,
      'active': true,
    },
    {
      'name': 'LuxStone Gallery',
      'company': 'LuxStone',
      'phone': '+91 40 9876 5432',
      'email': 'hyd@luxstone.com',
      'address': '88 Jubilee Hills',
      'city': 'Hyderabad',
      'state': 'Telangana',
      'pincode': '500033',
      'latitude': 17.3850,
      'longitude': 78.4867,
      'rating': 4.5,
      'verified': false,
      'active': true,
    },
  ];
  
  for (final dealer in dealers) {
    await supabase.from('dealers').upsert(dealer, onConflict: 'name');
  }
  print('✅ Dealers seeded');
}